apiVersion: v1
kind: Pod
metadata:
  name: nginx-liveness
  labels:
     app: nginx
spec:
  containers:
  - name: nginx-demo
    image: nginx:1.15-alpine
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 5
      timeoutSeconds: 1




----

apiVersion: v1
kind: Pod
metadata:
  name: liveness-tcp
  labels:
     app: livess-pro
spec:
  containers:
  - name: echo-server
    image: hashicorp/http-echo:0.2.3
    args: ["-listen", ":8080", "-text", "example for tcp liveness probe"]
    ports:
      - containerPort: 8080
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 1




------

apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-test-command
spec:
  containers:
  - name: liveness
    image: busybox:1.28
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 3000
    # ^ Create file and leave it, container will die after 3000s
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5   # Start initiation of probes after 5 seconds
      periodSeconds: 3   # check after every 3 second
      failureThreshold: 3  # Number of times to try before restarting the pod




-----
apiVersion: v1
kind: Pod
metadata:
  name: nginx-liveness-fail
  labels:
     app: nginx
spec:
  containers:
  - name: nginx-demo
    image: nginx:1.9.1
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 81
      initialDelaySeconds: 15
      timeoutSeconds: 1
