apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: "0.1"
  template:
    metadata:
      labels:
        app: frontend
        version: "0.1"
    spec:
      volumes:
      - name: nginx-ambassador-config
        configMap:
          name: nginx-ambassador-conf
      containers:
      - name: frontend
        image: teamcloudyuga/ambassador:ckad
        ports:
        - containerPort: 8080

      - name: backend
        image: nginx:1.15-alpine
        volumeMounts:
        - name: nginx-ambassador-config
          mountPath: /etc/nginx/conf.d/amba.conf
          subPath: "default.conf"  
